name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js (latest LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run formatter
        run: npm run format

      - name: Start app
        run: npm run dev &

      - name: Wait for app to be ready
        run: npx wait-on http://localhost:5173

      # - name: Extra wait for Vite/React hydration
      #   run: sleep 3

      - name: Run E2E tests
        run: npm run e2e

      # - name: Upload Playwright Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: playwright-e2e-debug
      #     path: |
      #       screenshot-ci.png
      #       page.html
      #       screenshot-error.png
      #       page-error.html
